services:
  gateway:
    build:
      context: ./gateway
      dockerfile: Dockerfile
    image: examples_scatter-by-distribution_gateway
    container_name: scatter-by-distribution_gateway
    ports:
      - "4000:4000"
    depends_on:
      - service_a
      - service_b
    networks:
      - scatter-by-distribution_network
    develop:
      watch:
        - action: rebuild
          path: ./gateway

  service_a:
    build:
      context: ./service_a
      dockerfile: Dockerfile
    image: examples_scatter-by-distribution_service_a
    container_name: scatter-by-distribution_service_a
    ports:
      - "4010:4010"
    networks:
      - scatter-by-distribution_network
    develop:
      watch:
        - action: rebuild
          path: ./service_a

  service_b:
    build:
      context: ./service_b
      dockerfile: Dockerfile
    image: examples_scatter-by-distribution_service_b
    container_name: scatter-by-distribution_service_b
    ports:
      - "4020:4020"
    networks:
      - scatter-by-distribution_network
    develop:
      watch:
        - action: rebuild
          path: ./service_b

networks:
  scatter-by-distribution_network:
    driver: bridge
    name: scatter-by-distribution_network
